version: 0.0.{build}-pre

configuration: Release

image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

nuget:
  project_feed: true

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity Minimal

build_script:
  - cmd: dotnet build src\Glued --configuration %CONFIGURATION%
  - cmd: dotnet build src\Glued.Selenium.WebDriver --configuration %CONFIGURATION%

after_build:
  - cmd: dotnet pack src\Glued --configuration %CONFIGURATION% --include-symbols --no-build --output ..\..\nupkgs /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
  - cmd: dotnet pack src\Glued.Selenium.WebDriver --configuration %CONFIGURATION% --include-symbols --no-build --output ..\..\nupkgs /p:PackageVersion=%APPVEYOR_BUILD_VERSION%

test_script:
  - cmd: dotnet test tests\Glued.UnitTests\Glued.UnitTests.csproj --configuration %CONFIGURATION%
  - cmd: dotnet test tests\Glued.Selenium.WebDriver.SpecFlowTests\Glued.Selenium.WebDriver.SpecFlowTests.csproj --configuration %CONFIGURATION%

artifacts:
  - path: nupkgs\*.nupkg